%PDF-1.3
%“Œ‹ž ReportLab Generated PDF document http://www.reportlab.com
1 0 obj
<<
/F1 2 0 R
>>
endobj
2 0 obj
<<
/BaseFont /Helvetica /Encoding /WinAnsiEncoding /Name /F1 /Subtype /Type1 /Type /Font
>>
endobj
3 0 obj
<<
/Contents 7 0 R /MediaBox [ 0 0 612 792 ] /Parent 6 0 R /Resources <<
/Font 1 0 R /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
>> /Rotate 0 /Trans <<

>> 
  /Type /Page
>>
endobj
4 0 obj
<<
/PageMode /UseNone /Pages 6 0 R /Type /Catalog
>>
endobj
5 0 obj
<<
/Author (anonymous) /CreationDate (D:20250516212926+00'00') /Creator (ReportLab PDF Library - www.reportlab.com) /Keywords () /ModDate (D:20250516212926+00'00') /Producer (ReportLab PDF Library - www.reportlab.com) 
  /Subject (unspecified) /Title (untitled) /Trapped /False
>>
endobj
6 0 obj
<<
/Count 1 /Kids [ 3 0 R ] /Type /Pages
>>
endobj
7 0 obj
<<
/Filter [ /ASCII85Decode /FlateDecode ] /Length 292
>>
stream
Gar>A>t`'h'RelB3:ppBaV+"1"88JT5]h2!Ll1s=g;kI4)fIKOs*j@^l&a*ei7rA`QRa5jOP<r"i)3u?PE<g]DicDDTl-!l6&3X%C+=0`(/PLY=cq%hf5]J%(FT-NL"a*?W->1-$m5*#ApR`jUqPZ:=8ChnA3O%[N&+0:4FT`gh7e-DK=;o1#uT;3(i*;Ul>gT@AI4=pM>+.J+0Y$FOl'e2)[lI7RSWI:KLeSEg;`1Z$*BZ1F]WUumO-#+The&2[hL4'Hk4b-74*\Ei7ge/J'@fV?A63"m[7@P~>endstream
endobj
xref
0 8
0000000000 65535 f 
0000000073 00000 n 
0000000104 00000 n 
0000000211 00000 n 
0000000404 00000 n 
0000000472 00000 n 
0000000768 00000 n 
0000000827 00000 n 
trailer
<<
/ID 
[<4b893e52c143f09ac3793f9f3e3bfcd6><4b893e52c143f09ac3793f9f3e3bfcd6>]
% ReportLab generated PDF document -- digest (http://www.reportlab.com)

/Info 5 0 R
/Root 4 0 R
/Size 8
>>
startxref
1209
%%EOF
